SELECT * FROM LIVER_PATIENT WHERE DIRECT_BILIRUBIN >(SELECT AVG(DIRECT_BILIRUBIN) FROM LIVER_PATIENT);

SELECT AVG(AAP) FROM LIVER_PATIENT WHERE AGE < 50;

SELECT GENDER,AVG(AGE),AVG(TOTAL_PROTIENS) FROM LIVER_PATIENT GROUP BY GENDER;

SELECT * FROM (SELECT GENDER,MAX(TOTAL_PROTIENS) AS HIGHEST_TOTAL_PROTIENS  FROM LIVER_PATIENT 
GROUP BY GENDER ORDER BY HIGHEST_TOTAL_PROTIENS DESC)
WHERE ROWNUM = 1;

SELECT * FROM(SELECT GENDER,AVG(TOTAL_PROTIENS) AS ATP FROM LIVER_PATIENT WHERE AGE<50 GROUP BY GENDER ORDER BY ATP DESC)
WHERE ROWNUM = 1;

SELECT * FROM(SELECT GENDER, AVG(TOTAL_BILIRUBIN), AVG(DIRECT_BILIRUBIN)FROM LIVER_PATIENT 
GROUP BY GENDER ORDER BY (AVG(TOTAL_BILIRUBIN)+ AVG(DIRECT_BILIRUBIN)) DESC)
WHERE ROWNUM = 1;
/*-------------------------------------------------------------------------------------------*/

SELECT * 
FROM LIVER_PATIENT
INNER JOIN STATUS ON LIVER_PATIENT.ID = STATUS.ID 
INNER JOIN CITY_NAME ON LIVER_PATIENT.CITY_CODE = CITY_NAME.CITY_CODE
INNER JOIN STATE_NAME ON LIVER_PATIENT.STATE_CODE = STATE_NAME.STATE_CODE 
WHERE liver_patient.DIRECT_BILIRUBIN > (
    SELECT AVG(DIRECT_BILIRUBIN) 
    FROM LIVER_PATIENT
);


SELECT AVG(lp.AAP) 
FROM LIVER_PATIENT lp
INNER JOIN STATUS s ON lp.ID = s.ID 
INNER JOIN CITY_NAME cc ON lp.city_code = cc.city_code 
INNER JOIN STATE_NAME sc ON lp.state_code = sc.state_code 
WHERE lp.AGE < 50;