select * from Liver_Patient_Dataset

ALTER TABLE Liver_Patient_Dataset
ADD CONSTRAINT ID_PK PRIMARY KEY (ID);
 
ALTER TABLE CITYCODE_STATECODE
ADD CONSTRAINT CITY_CODE_PK PRIMARY KEY (CITY_CODE);

ALTER TABLE STATE_CODE
ADD CONSTRAINT STATE_CODE_PK PRIMARY KEY (STATE_CODE);

ALTER TABLE lIVER_PATIENT_DATASET
ADD FOREIGN KEY (CITY_CODE)
REFERENCES CITYCODE_STATECODE(CITY_CODE);

ALTER TABLE lIVER_PATIENT_DATASET
ADD FOREIGN KEY (STATE_CODE)
REFERENCES STATE_CODE(STATE_CODE);

ALTER TABLE STATUS
ADD FOREIGN KEY (ID)
REFERENCES LIVER_PATIENT_DATASET(ID);

// 	Retrieve the liver patients with a direct bilirubin level higher than the average direct bilirubin level for all patients.

SELECT * 
FROM LIVER_PATIENT_DATASET
INNER JOIN STATUS ON LIVER_PATIENT_DATASET.ID = STATUS.ID 
INNER JOIN CITYCODE_STATECODE ON LIVER_PATIENT_DATASET.CITY_CODE = CITYCODE_STATECODE.CITY_CODE
INNER JOIN STATE_CODE ON LIVER_PATIENT_DATASET.STATE_CODE = STATE_CODE.STATE_CODE 
WHERE LIVER_PATIENT_DATASET.DIRECT_BILIRUBIN > (
    SELECT AVG(DIRECT_BILIRUBIN) 
    FROM LIVER_PATIENT_DATASET
);

// 	Retrieve average alkaline phosphatase level for liver patients under the age of 50

SELECT AVG(ALKPHOS_ALKALINE_PHOSPHOTASE) FROM LIVER_PATIENT_DATASET WHERE AGE_OF_THE_PATIENT < 50;

// 	Retrieve the average age and average total proteins for each gender

SELECT GENDER_OF_THE_PATIENT, AVG(AGE_OF_THE_PATIENT), AVG(TOTAL_PROTIENS) FROM LIVER_PATIENT_DATASET GROUP BY GENDER_OF_THE_PATIENT;

// 	Retrieve the gender with the highest total protein level
SELECT * FROM (SELECT GENDER_OF_THE_PATIENT, MAX(TOTAL_PROTIENS) AS HIGHEST_TOTAL_PROTIENS  FROM LIVER_PATIENT_DATASET 
GROUP BY GENDER_OF_THE_PATIENT ORDER BY HIGHEST_TOTAL_PROTIENS DESC)
WHERE ROWNUM = 1;

// 5.	Retrieve the gender with the highest average total protein level among liver patients below the age of 50

SELECT * FROM
(SELECT GENDER_OF_THE_PATIENT, AVG(TOTAL_PROTIENS) AS ATP FROM LIVER_PATIENT_DATASET 
WHERE AGE_OF_THE_PATIENT<50 
GROUP BY GENDER_OF_THE_PATIENT 
ORDER BY ATP DESC)
WHERE ROWNUM = 1;

// 6.	Retrieve the gender with the highest average total bilirubin and direct bilirubin levels

SELECT * FROM(SELECT GENDER_OF_THE_PATIENT, AVG(TOTAL_BILIRUBIN), AVG(DIRECT_BILIRUBIN)FROM LIVER_PATIENT_DATASET 
GROUP BY GENDER_OF_THE_PATIENT ORDER BY (AVG(TOTAL_BILIRUBIN)+ AVG(DIRECT_BILIRUBIN)) DESC)
WHERE ROWNUM = 1;

