select * from Liver_Patient_Dataset

ALTER TABLE Liver_Patient_Dataset
ADD CONSTRAINT ID_PK PRIMARY KEY (ID);
 
ALTER TABLE CITYCODE_STATECODE
ADD CONSTRAINT CITY_CODE_PK PRIMARY KEY (CITY_CODE);

ALTER TABLE STATE_CODE
ADD CONSTRAINT STATE_CODE_PK PRIMARY KEY (STATE_CODE);

ALTER TABLE lIVER_PATIENT_DATASET
ADD FOREIGN KEY (CITY_CODE)
REFERENCES CITYCODE_STATECODE(CITY_CODE);

ALTER TABLE lIVER_PATIENT_DATASET
ADD FOREIGN KEY (STATE_CODE)
REFERENCES STATE_CODE(STATE_CODE);

ALTER TABLE STATUS
ADD FOREIGN KEY (ID)
REFERENCES LIVER_PATIENT_DATASET(ID);